# Generated by Django 5.2.8 on 2025-11-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('serialNo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=30)),
                ('ProductId', models.IntegerField()),
                ('ManufactureDate', models.DateTimeField()),
                ('Price', models.IntegerField()),
                ('Quantity', models.IntegerField()),
            ],
        ),
    ]
