# Generated by Django 5.2.8 on 2025-11-21 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ProductId',
        ),
    ]
